// models/types/definitions/solid-env.d.ts
import type { TSolid } from '../processor';
/**
 * SOLIDIFIED TYPE DATABASE (AUTO-GENERATED)
 *
 * This file is managed by the 'is-solid' transformer.
 * It maps your string-based keys back to their original TypeScript interfaces,
 * enabling ambient autocompletion and type safety across your entire project
 * without manual imports.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes will be overwritten during the next build/sync.
 */
declare module 'is-solid' {
  export function isSolid(data: unknown): data is TSolid<'KEY-1', TTYPE_1>;

  export function isSolid(data: unknown): data is TSolid<'KEY-2', TTYPE_2>;
}
