import type { TSolidShape } from './blueprints';

/**
 * 📍 VAULT ENTRIES
 * Shredded GPS and Identity data for the Triple-KV system.
 */
export type TVaultManifestEntry = { area: string; filePath: string };
export type TVaultRegistryEntry = { symbolName: string; typeName: string };

/**
 * 🗄️ TRIPLE-KV SNAPSHOT
 * The persistence schema for vault-snapshot.json (The Bunker).
 */
export type TTripleKV = {
  blueprints: Record<string, TSolidShape>;
  manifest: Record<string, TVaultManifestEntry>;
  registry: Record<string, TVaultRegistryEntry>;
  references: Record<string, string>;
  version: string;
};

/**
 * 🛡️ TSOLID VAULT MAP
 * The live runtime memory structure for the Xalethor system.
 */
export type TSolidVaultMap = {
  /** The physical, flat structural DNA pool (keyed by Content Hashes like 'sh_sbug7v') */
  blueprints: Map<string, TSolidShape>;
  /** 🎯 NEW: Nominal Key -> Structural Content Hash mapping ('USER_TEST' -> 'sh_sbug7v') */
  references: Map<string, string>;
  manifest: Map<string, TVaultManifestEntry>;
  registry: Map<string, TVaultRegistryEntry>;
  errors: Map<string, TSolidError[]>;
  _isHydrated?: boolean;
};

/**
 * ⚠️ TSOLID ERROR
 * A detailed failure report generated by the Validation Engine.
 */
export type TSolidError = {
  key: string;
  path: string;
  message: string;
  expected: string | TSolidShape;
  received: unknown;
  area?: string; // Runtime failure GPS
  origin?: string | TVaultManifestEntry; // Definition GPS
};
/**
 * 🏷️ TXALOR RULE KIND
 * Explicit architectural categories for runtime data schema failures.
 */
export type TXalorRuleKind =
  | 'primitive_mismatch'
  | 'literal_mismatch'
  | 'missing_property'
  | 'excess_property'
  | 'union_exhausted'
  | 'intersection_breached'
  | 'depth_overflow';

/**
 * 📦 TXALOR ISSUE
 * A deeply detailed, scannable record representing a single structural violation.
 */
export type TXalorIssue = {
  /** The full dot-notation breadcrumb path matching the payload (e.g., '$.address.zip') */
  path: string;
  /** A human-readable description or stringified representation of the required shape */
  expected: string;
  /** A stringified JSON or primitive readout of the broken input that was provided */
  received: string;
  /** The specific type-system rule or boundary law that was violated */
  rule: TXalorRuleKind;
};

/**
 * 📊 TXALOR AUDIT REPORT
 * The unified return interface for soft-fail programmatic diagnostics.
 */
export type TXalorAuditReport = {
  /** Quick flag indicating if the data satisfies the target blueprint */
  valid: boolean;
  /** An array containing deterministic diagnostic traces for each failure found */
  issues: TXalorIssue[];
};
// TXalorAuditReport, TXalorIssue, TXalorRuleKind
