import type { TSolidShapeKinds } from '../models/types';
import { IS_SOLID_CONFIG_ITEMS } from '../models/constants';

/**
 * 💎 MESSAGE MANIFEST
 * The authoritative dictionary for all system failures.
 *
 * INVARIANTS:
 * - No logic allowed here. Purely templates and codes.
 * - Every key must map to a deterministic failure state.
 */

type TMessageHandlerParams = {
  path?: string;
  expected?: unknown;
  received?: unknown;
  key?: string;
  kind?: TSolidShapeKinds;
  version?: string;
  msg?: string;
  location?: string;
};
type TMessageHandler = Record<string, (props: TMessageHandlerParams) => string>;
type TMessageHandlerShape = {
  ERROR: TMessageHandler;
  WARNING: TMessageHandler;
};
export const XALOR_MESSAGE_HANDLER = {
  ERROR: {
    UNSUPPORTED_KIND: (props: TMessageHandlerParams) =>
      `[xalor] Unsupported shape kind: "${props.kind}". ` +
      `This usually happens if the metadata was generated by an incompatible version.`,
    DATABASE_VERSION_MIS_MATCH: (props: TMessageHandlerParams) =>
      `[xalor] Version mismatch for "${props.key}". Expected ${IS_SOLID_CONFIG_ITEMS.solidVersion}, got ${props.version}.`,
    COLLISION: (props: TMessageHandlerParams) =>
      `[xalor] 🚨 Collision! Key "${props.key}" is already registered. Check: ${props.msg}`,
    // MISSING_BLUEPRINT: (props) =>
    //   `[xalor] Runtime Error: No blueprint found for key "${props.key}". ` +
    //   `Ensure the file containing this type is being mined by the transformer.`,
    MISSING_VAULT_BLUEPRINT: (props) =>
      `[xalor] Blueprint missing for "${props.key}", though manifest exists at ${props.location}.`,
    MISSING_VAULT_KEY: (props) =>
      `[xalor] Key "${props.key}" is completely unknown to the Vault.`,
    BROKEN_PIPE_GENIES: (props) =>
      `[xalor-persist] Failed to write Genesis Cache: ${props.error}`,
    DEFINITION_COLLISION: (props: TMessageHandlerParams) =>
      `[xalor] 🚨 Collision: Key "${props.key}" is defined in ${props.path} and ${props.path}.`,
  } as const,
  WARNING: {
    COLLISION: (props: TMessageHandlerParams) =>
      `[xalor] ⚠️ Collision detected for key "${props.key}". Overwriting existing entry.`,
    DEPRECATED_ACCESS: (props) =>
      `[xalor] ⚠️ Accessing 'items' map is deprecated. Please use 'blueprints' or 'manifest' instead.`,
  } as const,
};

// TYPE_MISMATCH: (path: string, exp: string, rec: any) =>
//   `[isSolid] Type mismatch at '${path}': Expected ${exp}, received ${typeof rec}.`,
// LITERAL_MISMATCH: (path: string, exp: any) =>
//   `[isSolid] Literal mismatch at '${path}': Expected the specific value: ${exp}.`,
// MISSING_KEY: (path: string) =>
//   `[isSolid] Required property '${path}' is missing.`,
// UNION_FAIL: (path: string) =>
//   `[isSolid] Data at '${path}' failed to solidify against any allowed union branches.`,
// VAULT_MISSING: (key: string) =>
//   `[isSolid] Ambient lookup failed: '${key}' does not exist in the Registry.`,
// `[xalor] Collision: Key "${props.key}" is already defined in ${existing.filePath}.`
