import type { TSolidShapeKinds } from '../models/types';

/**
 * 💎 MESSAGE MANIFEST
 * The authoritative dictionary for all system failures.
 *
 * INVARIANTS:
 * - No logic allowed here. Purely templates and codes.
 * - Every key must map to a deterministic failure state.
 */

type TMessageHandlerParams = {
  path: string;
  expected?: unknown;
  received?: unknown;
  key?: string;
  kind?: TSolidShapeKinds;
};
type TMessageHandler = Record<string, (props: TMessageHandlerParams) => string>;
type TMessageHandlerShape = {
  ERROR: TMessageHandler;
  WARNING: TMessageHandler;
};
export const XALOR_MESSAGE_HANDLER: TMessageHandlerShape = {
  ERROR: {
    UNSUPPORTED_KIND: (props: TMessageHandlerParams) =>
      `[xalor] Unsupported shape kind: "${props.kind}". ` +
      `This usually happens if the metadata was generated by an incompatible version.`,
  },
  WARNING: {
    COLLISION: (props: TMessageHandlerParams) =>
      `[xalor] ⚠️ Collision detected for key "${props.key}". Overwriting existing entry.`,
  },
  // TYPE_MISMATCH: (path: string, exp: string, rec: any) =>
  //   `[isSolid] Type mismatch at '${path}': Expected ${exp}, received ${typeof rec}.`,
  // LITERAL_MISMATCH: (path: string, exp: any) =>
  //   `[isSolid] Literal mismatch at '${path}': Expected the specific value: ${exp}.`,
  // MISSING_KEY: (path: string) =>
  //   `[isSolid] Required property '${path}' is missing.`,
  // UNION_FAIL: (path: string) =>
  //   `[isSolid] Data at '${path}' failed to solidify against any allowed union branches.`,
  // VAULT_MISSING: (key: string) =>
  //   `[isSolid] Ambient lookup failed: '${key}' does not exist in the Registry.`,
} satisfies TMessageHandlerShape;
