// src/validation/solidify-shape.ts
import type { TValidationContext, TSolidShape } from '../models/types';
import { createInitialContext } from './context';
import { isObject, isNull, isFunction } from '../utils/guards';
import { VALIDATORS } from './validation-mapper';
/**
 * 💎 solidify
 * Attests that raw data conforms to a TSolidShape blueprint.
 *
 * INVARIANTS:
 * - Prevents infinite recursion via Graph Integrity checks (ctx.seen).
 * - Routes execution to the specialized Validator Mapper.
 */

export function solidifyShape(
  data: unknown,
  shape: TSolidShape,
  ctx: TValidationContext = createInitialContext(),
): boolean {
  // TODO: Handle Recursion Protection
  if (isObject(data) && !isNull(data)) {
    const validatedShapes = ctx.seen.get(data);
    if (validatedShapes?.has(shape)) return true;

    if (!validatedShapes) {
      ctx.seen.set(data, new Set([shape]));
    } else {
      validatedShapes.add(shape);
    }
  }
  const validator = VALIDATORS[shape.kind];
  if (!isFunction(validator)) {
    throw new Error(
      `[xalor] Unsupported shape kind: "${shape.kind}". ` +
        `This usually happens if the metadata was generated by an incompatible version.`,
    );
  }
  return validator(data, shape, ctx);
}
