// src/validation/unions.ts
import type {
  TValidationContext,
  // TSolidUnionShape,
  TSolidShape,
} from '../models/types';
import { validate } from './index';
import { reportError } from './errors';

// export function validateUnion(
//   data: unknown,
//   shape: TSolidUnionShape,
//   ctx: TValidationContext,
// ): boolean {
//   const snapshotCount = ctx.errors.length;

//   const isValid = shape.values.some((subShape) => {
//     const branchIsValid = validate(data, subShape, ctx);

//     if (branchIsValid) {
//       ctx.errors.splice(snapshotCount);
//       return true;
//     }
//     return false;
//   });

//   if (!isValid) {
//     reportError(ctx, shape, data);
//   }

//   return isValid;
// }
export function validateUnion(
  data: unknown,
  shape: Extract<TSolidShape, { kind: 'union' }>,
  ctx: TValidationContext,
): boolean {
  const snapshotCount = ctx.errors.length;

  for (const subShape of shape.values) {
    if (validate(data, subShape, ctx)) {
      // Clear errors generated by this branch's failed attempts
      if (ctx.errors.length > snapshotCount) {
        ctx.errors.splice(snapshotCount);
      }
      return true;
    }
  }

  return reportError(ctx, shape, data);
}
