// src/validation/validators.ts
import { validateShape } from './validate-shape';
import type {
  TSolidArrayShape,
  TValidationContext,
  TSolidObjectRawShape,
  TSolidShape,
  TSolidIntersectionShape,
  TSolidReferenceShape,
  TSolidLiteralShape,
  TSolidPrimitiveShape,
} from '../models/types';
import { reportError } from './errors';
import {
  isArray,
  isObject,
  isNull,
  isRecord,
  isPrimitive,
} from '../utils/guards';
import { yieldEntries, yieldFiltered } from '../utils';
import { XalethorService } from '../xalor-service';

/**
 * 💎 Collection Validators
 * Optimized for O(1) memory and fast-bailout.
 */
export function validateArray(
  data: unknown,
  shape: TSolidArrayShape,
  ctx: TValidationContext,
): boolean {
  if (!isArray(data)) return reportError(ctx, 'array', data);

  const originalPath = ctx.path;

  for (let i = 0; i < data.length; i++) {
    ctx.path = `${originalPath}[${i}]`; // Standard array notation
    if (!validateShape(data[i], shape.items, ctx)) {
      ctx.path = originalPath;
      return false;
    }
  }

  ctx.path = originalPath;
  return true;
}

/**
 *
 * @param data
 * @param shape
 * @param ctx
 * @returns
 */
export function validateObject(
  data: unknown,
  shape: { properties: Record<string, TSolidObjectRawShape> },
  ctx: TValidationContext,
): boolean {
  /* prettier-ignore */ if (!isObject(data) || isNull(data) || !isRecord(data))  return reportError(ctx, 'object', data);

  const originalPath = ctx.path;
  // yieldEntries for O(1)
  const propertyEntries = yieldEntries(
    shape.properties,
    (_key): _key is string => true,
  );

  for (const [key, metadata] of propertyEntries) {
    const value = data[key];
    ctx.path = originalPath === '$' ? key : `${originalPath}.${key}`;

    if (value === undefined) {
      if (metadata.optional) continue;
      const result = reportError(ctx, metadata.shape, 'missing');
      ctx.path = originalPath;
      return result;
    }

    // 2. Recurse
    if (!validateShape(value, metadata.shape, ctx)) {
      ctx.path = originalPath;
      return false;
    }
  }

  ctx.path = originalPath;
  return true;
}

/**
 * 💎 Graph Validators
 * Handles branch logic and type-graph fragments.
 */
export function validateUnion(
  data: unknown,
  shape: Extract<TSolidShape, { kind: 'union' }>,
  ctx: TValidationContext,
): boolean {
  const snapshotCount = ctx.errors.length;

  for (const subShape of shape.values) {
    if (validateShape(data, subShape, ctx)) {
      // Clear errors generated by this branch's failed attempts
      if (ctx.errors.length > snapshotCount) {
        ctx.errors.splice(snapshotCount);
      }
      return true;
    }
  }

  return reportError(ctx, shape, data);
}
export function validateIntersection(
  data: unknown,
  shape: TSolidIntersectionShape,
  ctx: TValidationContext,
): boolean {
  // Use yieldFiltered to only grab valid shapes from the intersection
  const parts = yieldFiltered(
    shape.parts,
    (_part): _part is TSolidShape => true,
  );

  for (const part of parts) {
    if (!validateShape(data, part, ctx)) {
      return false;
    }
  }

  return true;
}
/**
 * 💎 Ambient Database Bridge
 * Handles "Solid" type resolution via the Global Vault.
 */

export function validateReference(
  data: unknown,
  shape: TSolidReferenceShape,
  ctx: TValidationContext,
): boolean {
  // Pillar 2 in action: Resolve the ghost type by its string key
  const metadata = XalethorService.inspectMetaData(shape.name);

  if (!metadata) {
    return reportError(
      ctx,
      `Registered Shape: ${shape.name}`,
      'Missing from Vault',
    );
  }

  // Recurse using the actual metadata found in the Registry
  return validateShape(data, metadata.shape, ctx);
}
/**
 * 💎 Internal Utility
 * Validates a primitive value against a specific type string.
 */
export function validatePrimitive(
  data: unknown,
  shape: TSolidPrimitiveShape,
  ctx: TValidationContext,
): boolean {
  const { type } = shape;
  if (type === 'unknown') return true;

  const isValid = typeof data === type && isPrimitive(data);

  return isValid ? true : reportError(ctx, type, data);
}
/**
 * 💎 Internal Utility
 * Validates a value against a literal constant.
 */
export function validateLiteral(
  data: unknown,
  shape: TSolidLiteralShape,
  ctx: TValidationContext,
): boolean {
  return data === shape.value ? true : reportError(ctx, shape, data);
}
