import {
  USER_AGENT_BRAND_PATTERNS,
  USER_AGENT_DEVICE_PATTERNS,
  USER_AGENT_OS_PATTERNS,
  USER_AGENT_BROWSER_PATTERNS,
} from './user-agent';
import { REGEX_DATE_PATTERNS } from './date';
import { REGEX_COLOR_PATTERNS } from './color';

export const REGEX_CENTRAL_PATTERN_SOURCE = {
  ...REGEX_COLOR_PATTERNS,
  ...REGEX_DATE_PATTERNS,
  ...USER_AGENT_BRAND_PATTERNS,
  ...USER_AGENT_DEVICE_PATTERNS,
  ...USER_AGENT_OS_PATTERNS,
  ...USER_AGENT_BROWSER_PATTERNS,
} as const;
